import {deleteSite, deleteUser, enableModule} from '@jahia/cypress';
import {
    createSiteWithLoginPage,
    createUserForMFA,
    deleteAllEmails,
    getEmailBody,
    initiate,
    installMFAConfig,
    prepareEmailCodeFactor
} from './utils';
import {faker} from '@faker-js/faker';

describe('Tests for the email template', () => {
    let username: string;
    let password: string;
    let email: string;

    beforeEach(() => {
        installMFAConfig('email-template.yml'); // Tests might change the MFA config
        username = faker.internet.username();
        password = faker.internet.password();
        email = faker.internet.email();
        createUserForMFA(username, password, email);
        deleteAllEmails(); // Sanity cleanup
        cy.logout(); // Ensure to start with an unauthenticated session
    });

    afterEach(() => {
        deleteUser(username);
        deleteAllEmails();
    });

    it('Should get the fallback email template when not using any site', () => {
    // GIVEN: No site created

        // WHEN: Initiating the MFA process
        initiate(username, password);
        prepareEmailCodeFactor();

        // THEN: The email body should be as expected
        getEmailBody(email).then(body => {
            assertIsFallbackTemplate(body);
        });
    });

    it('Should get the fallback email template when using a site but without a custom email template', () => {
    // GIVEN: A site without a custom email template provided by a module
        const siteKey = faker.lorem.slug();
        createSiteWithLoginPage(siteKey, undefined, undefined, []);

        // WHEN: Initiating the MFA process
        initiate(username, password, siteKey);
        prepareEmailCodeFactor();

        // THEN: The email body should be as expected
        getEmailBody(email).then(body => {
            assertIsFallbackTemplate(body);
        });

        // Cleanup
        deleteSite(siteKey);
    });

    it('Should get the custom email template when using a site with a custom email template', () => {
    // GIVEN: A site without a custom email template provided by a module
        const siteKey = faker.lorem.slug();
        createSiteWithLoginPage(siteKey, undefined, undefined, []);
        enableModule('user-password-authentication-ui', siteKey); // The UI module provides a custom email template

        // WHEN: Initiating the MFA process
        initiate(username, password, siteKey);
        prepareEmailCodeFactor();

        // THEN: The email body should be as expected
        getEmailBody(email).then(body => {
            expect(body).to.contain(
                '<!-- rendered by \'user-password-authentication-ui\' module -->',
                'not generated by the correct module'
            );
            expect(body).to.contain('<title>Authentication Code</title>');

            expect(body).to.contain('<p data-testid="email-message" style="margin: 0; padding: 0;">Hello,<br/>Use the following code to complete your authentication:</p>');
            expect(body).to.contain('<p data-testid="validity" style="margin: 0; padding: 0;">This code is valid for <strong>15 minutes</strong>.</p>');
            expect(body).to.contain('<p data-testid="footer-title" style="margin: 0; padding: 0;">Didn\'t request this code?</p>');
            expect(body).to.contain(
                '<p data-testid="footer-text" style="margin: 0; padding: 0;">If you didn\'t request this code, secure your account immediately by <a style="color: #00A0E3; text-decoration: underline; display: inline-block;" href="https://support.jahia.com/">changing your password</a>.<br/>If you need assistance, <a style="color: #00A0E3; text-decoration: underline; display: inline-block;" href="https://support.jahia.com/">reach out to support</a><br/><br/>Regards,<br/>The Jahia Team</p>'
            );
            // Make sure the placeholder for the code is replaced
            expect(body).to.match(
                /<span data-testid="code">(\d{6})<\/span>/,
                'the placeholder should be replaced by a code'
            );
        });

        // Cleanup
        deleteSite(siteKey);
    });

    it('Should correctly resolve the server name when generating URLs in a custom email template', () => {
    // GIVEN: A site with a server name and a module with a custom email template enabled
        const siteKey = faker.lorem.slug();
        const serverName = faker.internet.domainName();
        createSiteWithLoginPage(siteKey, undefined, serverName, []);
        enableModule(
            'user-password-authentication-mfa-custom-email-code-template-test-module',
            siteKey
        );

        // WHEN: Initiating the MFA process
        initiate(username, password, siteKey);
        prepareEmailCodeFactor();

        // THEN: The email body should contain the correct server name in the URL attributes
        getEmailBody(email).then(body => {
            expect(body).to.contain(
                '<!-- rendered by \'user-password-authentication-mfa-custom-email-code-template-test-module\' module -->',
                'not generated by the correct module'
            );
            expect(body).to.contain('<h2>This is a custom mail code template</h2>');
            expect(body).to.match(
                /<span data-testid="code">(\d{6})<\/span>/,
                'the placeholder should be replaced by a code'
            );
            expect(body).to.contain(
                `<img src="http://${serverName}:8080/modules/user-password-authentication-mfa-custom-email-code-template-test-module/img/poweredByJahia.png" alt="Powered by Jahia">`
            );
        });

        // Cleanup
        deleteSite(siteKey);
    });

    const assertIsFallbackTemplate = (body: string) => {
        expect(body).to.contain('<title>Authentication Code</title>');
        expect(body).to.contain(
            '<!-- rendered by \'user-password-authentication-api\' module -->',
            'not generated by the correct module'
        );
        expect(body).to.contain('<p data-testid="email-message">Hello,<br/>Use the following code to complete your authentication:</p>');
        // Make sure the placeholder for the code is replaced
        expect(body).to.match(
            /<span data-testid="code">(\d{6})<\/span>/,
            'the placeholder should be replaced by a code'
        );
    };
});
