name: On merge to main

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  on-merge:
    secrets: inherit
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-on-merge.yml@reusable-on-merge
